#!/usr/bin/env bash
#
# test_markdownlint_validation.sh - Tests for the markdownlint validation loop
#
# Exercises the helper functions and validation flow added to
# generate-spec-from-issue.sh for Phase 7 (markdownlint validation).
#
# Usage: bash test_markdownlint_validation.sh
#
# Prerequisites: npx, markdownlint-cli2

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PASS=0
FAIL=0
TESTS_RUN=0

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------
assert_eq() {
    local test_name="$1" expected="$2" actual="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$expected" == "$actual" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected: $expected"
        echo "    actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local test_name="$1" needle="$2" haystack="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$haystack" | grep -qF "$needle"; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected to contain: $needle"
        echo "    actual: $haystack"
        FAIL=$((FAIL + 1))
    fi
}

assert_exit_code() {
    local test_name="$1" expected_code="$2"
    shift 2
    TESTS_RUN=$((TESTS_RUN + 1))
    local actual_code=0
    "$@" || actual_code=$?
    if [[ $actual_code -eq $expected_code ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected exit code: $expected_code"
        echo "    actual exit code:   $actual_code"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# Source the functions under test.
#
# We need the markdownlint validation helpers from generate-spec-from-issue.sh.
# To avoid running the main script body (which requires env vars and runs the
# full pipeline), we extract just the function definitions between known
# section markers.  This is safe because both files are in the same repo and
# the markers are stable section headers maintained by the same team.
# ---------------------------------------------------------------------------

# We need these vars to be set for the helper functions.
COPILOT_MODEL="${COPILOT_MODEL:-test-model}"
MARKDOWNLINT_PROMPT_MAX_CHARS=32000

# Footer management functions (duplicated here to avoid sourcing the full script)
_strip_footer_from_text() {
    local text="$1"
    printf '%s' "$text" | sed -E ':a;N;$!ba;s/\n*\n---\n\*Generated by Copilot SDK \([^)]*\)\*[[:space:]]*$//'
}

strip_model_footer() {
    _strip_footer_from_text "$1"
}

append_model_footer() {
    local file="$1"
    local content
    content=$(_strip_footer_from_text "$(cat "$file")")
    printf '%s' "$content" > "$file"
    printf '\n\n---\n*Generated by Copilot SDK (%s)*\n' "$COPILOT_MODEL" >> "$file"
}

# Extract markdownlint validation functions from the main script using sed.
# This reads the section between the "Markdownlint Validation" and "Phase
# Functions" markers and sources it directly.
_extracted_functions=$(sed -n '/^# ========================== Markdownlint Validation/,/^# ========================== Phase Functions/p' "$SCRIPT_DIR/generate-spec-from-issue.sh" | head -n -1)

# Source the extracted function definitions
source /dev/stdin <<< "$_extracted_functions"

# ---------------------------------------------------------------------------
# Test: parse_markdownlint_output
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: parse_markdownlint_output ==="

# T1: Standard violation format with column and error keyword (v0.22+)
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 error MD041/first-line-heading First line should be a heading")
assert_contains "parses filename" "specs/test/spec.md" "$output"
assert_contains "parses line number" "10" "$output"
assert_contains "parses rule" "MD041/first-line-heading" "$output"

# T2: Empty input
output=$(parse_markdownlint_output "")
assert_eq "empty input returns empty" "" "$output"

# T3: Multiple violations (with error keyword)
input="file1.md:1:1 error MD041/first-line-heading First line should be a heading
file2.md:50:81 error MD013/line-length Line length 205 > 200"
output=$(parse_markdownlint_output "$input")
count=$(echo "$output" | wc -l)
assert_eq "parses multiple violations" "2" "$count"

# T3b: Legacy format without error keyword
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 MD041/first-line-heading First line should be a heading")
assert_contains "parses legacy format" "MD041/first-line-heading" "$output"

# ---------------------------------------------------------------------------
# Test: compute_violation_fingerprint
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: compute_violation_fingerprint ==="

# T4: Empty violations
fp=$(compute_violation_fingerprint "")
assert_eq "empty violations fingerprint" "empty" "$fp"

# T5: Same violations produce same fingerprint
violations="file.md	10	1	MD041/first-line-heading	First line should be heading"
fp1=$(compute_violation_fingerprint "$violations")
fp2=$(compute_violation_fingerprint "$violations")
assert_eq "deterministic fingerprint" "$fp1" "$fp2"

# T6: Different violations produce different fingerprints
violations2="file.md	20	1	MD013/line-length	Line too long"
fp3=$(compute_violation_fingerprint "$violations2")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$fp1" != "$fp3" ]]; then
    echo "  ✓ different violations give different fingerprints"
    PASS=$((PASS + 1))
else
    echo "  ✗ different violations give different fingerprints"
    FAIL=$((FAIL + 1))
fi

# ---------------------------------------------------------------------------
# Test: check_npx_available
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: check_npx_available ==="

# T7: npx should be available in CI
assert_exit_code "npx is available" 0 check_npx_available

# ---------------------------------------------------------------------------
# Test: Auto-fix path (T006 — auto-fixable violations resolved without LLM)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Auto-fix path ==="

TMPDIR_TEST=$(mktemp -d /tmp/mdlint-test-autofix.XXXXXX)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# Create a file with trailing spaces (auto-fixable by markdownlint --fix)
cat > "$TMPDIR_TEST/test.md" << 'EOF'
# Test Document

This line has trailing spaces   
And this one too   

## Section Two

Content here.
EOF

# Verify violations exist before auto-fix
lint_before_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_before_exit=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $lint_before_exit -ne 0 ]]; then
    echo "  ✓ pre-auto-fix: violations detected"
    PASS=$((PASS + 1))
else
    echo "  ✗ pre-auto-fix: expected violations but got clean lint"
    FAIL=$((FAIL + 1))
fi

# Run auto-fix
npx markdownlint-cli2 --no-globs --fix "$TMPDIR_TEST/test.md" 2>/dev/null || true

# Verify violations resolved
lint_after_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_after_exit=$?
assert_eq "post-auto-fix: no violations" "0" "$lint_after_exit"

# ---------------------------------------------------------------------------
# Test: Empty spec directory (EC9)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Empty spec directory ==="

TMPDIR_EMPTY=$(mktemp -d /tmp/mdlint-test-empty.XXXXXX)

# Stub call_llm so it's never called
call_llm() { echo "ERROR: call_llm should not be called" >&2; return 1; }

MARKDOWNLINT_MAX_ITERATIONS=5
exit_code=0
run_markdownlint_validation "$TMPDIR_EMPTY" 2>/dev/null || exit_code=$?
assert_eq "empty dir returns success" "0" "$exit_code"

rm -rf "$TMPDIR_EMPTY"

# ---------------------------------------------------------------------------
# Test: run_markdownlint_validation with auto-fixable violations
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Full validation loop (auto-fix only) ==="

TMPDIR_FULL=$(mktemp -d /tmp/mdlint-test-full.XXXXXX)

# Create a file with auto-fixable violations only
cat > "$TMPDIR_FULL/spec.md" << 'EOF'
# Test Spec

Content with trailing whitespace   

## Details

More content here.   
EOF

exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_FULL" 2>&1) || exit_code=$?
assert_eq "auto-fix validation succeeds" "0" "$exit_code"
assert_contains "reports success" "SUCCESS" "$output"

rm -rf "$TMPDIR_FULL"

# ---------------------------------------------------------------------------
# Test: Max iteration exhaustion (T018)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Max iteration exhaustion ==="

TMPDIR_EXHAUST=$(mktemp -d /tmp/mdlint-test-exhaust.XXXXXX)

# Create a file with a violation that auto-fix can't resolve and LLM can't fix
# (since call_llm is stubbed to fail)
# MD013 (line-length > 200) is NOT auto-fixable — requires intelligent line breaking
python3 -c "
print('# Heading')
print()
words = 'the quick brown fox jumps over the lazy dog and keeps running through the vast open fields '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
" > "$TMPDIR_EXHAUST/spec.md"

# Override call_llm to always fail (simulates LLM unavailability)
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_EXHAUST" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ exhaustion returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ exhaustion returns non-zero (got exit 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports failure" "FAILED" "$output"

rm -rf "$TMPDIR_EXHAUST"

# ---------------------------------------------------------------------------
# Test: Lint fails but violations unparseable (Comment 2 regression test)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Lint exit non-zero with unparseable output ==="

TMPDIR_UNPARSE=$(mktemp -d /tmp/mdlint-test-unparse.XXXXXX)

# Create a valid file so the function proceeds past the empty-dir guard
cat > "$TMPDIR_UNPARSE/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Override parse_markdownlint_output to always return empty (simulates
# an unexpected output format that the parser can't handle)
_orig_parse=$(declare -f parse_markdownlint_output)
parse_markdownlint_output() { echo ""; }

# Override npx to simulate lint failure with unparseable output:
# first call (--fix) succeeds, second call (check-only) fails
_npx_call_count=0
npx() {
    _npx_call_count=$((_npx_call_count + 1))
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    echo "some unexpected markdownlint output format"
    return 1
}

call_llm() { return 1; }
MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_UNPARSE" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ unparseable lint failure returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ unparseable lint failure should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports unparseable failure" "FAILED" "$output"

# Restore originals
eval "$_orig_parse"
unset -f npx
unset _npx_call_count

rm -rf "$TMPDIR_UNPARSE"

# ---------------------------------------------------------------------------
# Test: $SPEC_DIR scoping (T025 — files outside spec dir are not modified)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: SPEC_DIR scoping ==="

TMPDIR_SCOPE=$(mktemp -d /tmp/mdlint-test-scope.XXXXXX)
mkdir -p "$TMPDIR_SCOPE/specdir"

# Put a valid file in the spec dir
cat > "$TMPDIR_SCOPE/specdir/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Put a file with violations OUTSIDE spec dir
cat > "$TMPDIR_SCOPE/outside.md" << 'EOF'
no heading at start which is a violation   
EOF

OUTSIDE_BEFORE=$(cat "$TMPDIR_SCOPE/outside.md")

# Override call_llm to avoid actual LLM calls
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=1
run_markdownlint_validation "$TMPDIR_SCOPE/specdir" 2>/dev/null || true

OUTSIDE_AFTER=$(cat "$TMPDIR_SCOPE/outside.md")

assert_eq "outside file unchanged" "$OUTSIDE_BEFORE" "$OUTSIDE_AFTER"

rm -rf "$TMPDIR_SCOPE"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "======================================="
echo "Tests: $TESTS_RUN  Passed: $PASS  Failed: $FAIL"
echo "======================================="

if [[ $FAIL -gt 0 ]]; then
    exit 1
fi
exit 0
