#!/usr/bin/env bash
#
# test_markdownlint_validation.sh - Tests for the markdownlint validation loop
#
# Exercises the helper functions and validation flow added to
# generate-spec-from-issue.sh for Phase 7 (markdownlint validation).
#
# Usage: bash test_markdownlint_validation.sh
#
# Prerequisites: npx, markdownlint-cli2

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PASS=0
FAIL=0
TESTS_RUN=0

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------
assert_eq() {
    local test_name="$1" expected="$2" actual="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$expected" == "$actual" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected: $expected"
        echo "    actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local test_name="$1" needle="$2" haystack="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$haystack" | grep -qF "$needle"; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected to contain: $needle"
        echo "    actual: $haystack"
        FAIL=$((FAIL + 1))
    fi
}

assert_exit_code() {
    local test_name="$1" expected_code="$2"
    shift 2
    TESTS_RUN=$((TESTS_RUN + 1))
    local actual_code=0
    "$@" || actual_code=$?
    if [[ $actual_code -eq $expected_code ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected exit code: $expected_code"
        echo "    actual exit code:   $actual_code"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# Source the functions under test.
#
# We need the markdownlint validation helpers from generate-spec-from-issue.sh.
# To avoid running the main script body (which requires env vars and runs the
# full pipeline), we extract just the function definitions between known
# section markers.  This is safe because both files are in the same repo and
# the markers are stable section headers maintained by the same team.
# ---------------------------------------------------------------------------

# We need these vars to be set for the helper functions.
COPILOT_MODEL="${COPILOT_MODEL:-test-model}"
MARKDOWNLINT_PROMPT_MAX_CHARS=32000

# Footer management functions (duplicated here to avoid sourcing the full script)
_strip_footer_from_text() {
    local text="$1"
    printf '%s' "$text" | sed -E ':a;N;$!ba;s/\n*\n---\n\*Generated by Copilot SDK \([^)]*\)\*[[:space:]]*$//'
}

strip_model_footer() {
    _strip_footer_from_text "$1"
}

append_model_footer() {
    local file="$1"
    local content
    content=$(_strip_footer_from_text "$(cat "$file")")
    printf '%s' "$content" > "$file"
    printf '\n\n---\n*Generated by Copilot SDK (%s)*\n' "$COPILOT_MODEL" >> "$file"
}

# Extract markdownlint validation functions from the main script using sed.
# This reads the section between the "Markdownlint Validation" and "Phase
# Functions" markers and sources it directly.
_extracted_functions=$(sed -n '/^# ========================== Markdownlint Validation/,/^# ========================== Phase Functions/p' "$SCRIPT_DIR/generate-spec-from-issue.sh" | head -n -1)

# Source the extracted function definitions
source /dev/stdin <<< "$_extracted_functions"

# ---------------------------------------------------------------------------
# Test: parse_markdownlint_output
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: parse_markdownlint_output ==="

# T1: Standard violation format with column and error keyword (v0.22+)
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 error MD041/first-line-heading First line should be a heading")
assert_contains "parses filename" "specs/test/spec.md" "$output"
assert_contains "parses line number" "10" "$output"
assert_contains "parses rule" "MD041/first-line-heading" "$output"

# T2: Empty input
output=$(parse_markdownlint_output "")
assert_eq "empty input returns empty" "" "$output"

# T3: Multiple violations (with error keyword)
input="file1.md:1:1 error MD041/first-line-heading First line should be a heading
file2.md:50:81 error MD013/line-length Line length 205 > 200"
output=$(parse_markdownlint_output "$input")
count=$(printf '%s\n' "$output" | awk 'END{print NR}')
assert_eq "parses multiple violations" "2" "$count"

# T3b: Legacy format without error keyword
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 MD041/first-line-heading First line should be a heading")
assert_contains "parses legacy format" "MD041/first-line-heading" "$output"

# ---------------------------------------------------------------------------
# Test: compute_violation_fingerprint
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: compute_violation_fingerprint ==="

# T4: Empty violations
fp=$(compute_violation_fingerprint "")
assert_eq "empty violations fingerprint" "empty" "$fp"

# T5: Same violations produce same fingerprint
violations="file.md	10	1	MD041/first-line-heading	First line should be heading"
fp1=$(compute_violation_fingerprint "$violations")
fp2=$(compute_violation_fingerprint "$violations")
assert_eq "deterministic fingerprint" "$fp1" "$fp2"

# T6: Different violations produce different fingerprints
violations2="file.md	20	1	MD013/line-length	Line too long"
fp3=$(compute_violation_fingerprint "$violations2")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$fp1" != "$fp3" ]]; then
    echo "  ✓ different violations give different fingerprints"
    PASS=$((PASS + 1))
else
    echo "  ✗ different violations give different fingerprints"
    FAIL=$((FAIL + 1))
fi

# ---------------------------------------------------------------------------
# Test: check_npx_available
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: check_npx_available ==="

# T7: npx should be available in CI
assert_exit_code "npx is available" 0 check_npx_available

# ---------------------------------------------------------------------------
# Test: Auto-fix path (T006 — auto-fixable violations resolved without LLM)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Auto-fix path ==="

TMPDIR_TEST=$(mktemp -d /tmp/mdlint-test-autofix.XXXXXX)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# Create a file with trailing spaces (auto-fixable by markdownlint --fix)
cat > "$TMPDIR_TEST/test.md" << 'EOF'
# Test Document

This line has trailing spaces   
And this one too   

## Section Two

Content here.
EOF

# Verify violations exist before auto-fix
lint_before_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_before_exit=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $lint_before_exit -ne 0 ]]; then
    echo "  ✓ pre-auto-fix: violations detected"
    PASS=$((PASS + 1))
else
    echo "  ✗ pre-auto-fix: expected violations but got clean lint"
    FAIL=$((FAIL + 1))
fi

# Run auto-fix
npx markdownlint-cli2 --no-globs --fix "$TMPDIR_TEST/test.md" 2>/dev/null || true

# Verify violations resolved
lint_after_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_after_exit=$?
assert_eq "post-auto-fix: no violations" "0" "$lint_after_exit"

# ---------------------------------------------------------------------------
# Test: Empty spec directory (EC9)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Empty spec directory ==="

TMPDIR_EMPTY=$(mktemp -d /tmp/mdlint-test-empty.XXXXXX)

# Stub call_llm so it's never called
call_llm() { echo "ERROR: call_llm should not be called" >&2; return 1; }

MARKDOWNLINT_MAX_ITERATIONS=5
exit_code=0
run_markdownlint_validation "$TMPDIR_EMPTY" 2>/dev/null || exit_code=$?
assert_eq "empty dir returns success" "0" "$exit_code"

rm -rf "$TMPDIR_EMPTY"

# ---------------------------------------------------------------------------
# Test: run_markdownlint_validation with auto-fixable violations
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Full validation loop (auto-fix only) ==="

TMPDIR_FULL=$(mktemp -d /tmp/mdlint-test-full.XXXXXX)

# Create a file with auto-fixable violations only
cat > "$TMPDIR_FULL/spec.md" << 'EOF'
# Test Spec

Content with trailing whitespace   

## Details

More content here.   
EOF

exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_FULL" 2>&1) || exit_code=$?
assert_eq "auto-fix validation succeeds" "0" "$exit_code"
assert_contains "reports success" "SUCCESS" "$output"

rm -rf "$TMPDIR_FULL"

# ---------------------------------------------------------------------------
# Test: Max iteration exhaustion (T018)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Max iteration exhaustion ==="

TMPDIR_EXHAUST=$(mktemp -d /tmp/mdlint-test-exhaust.XXXXXX)

# Create a file with a violation that auto-fix can't resolve and LLM can't fix
# (since call_llm is stubbed to fail)
# MD013 (line-length > 200) is NOT auto-fixable — requires intelligent line breaking
python3 -c "
print('# Heading')
print()
words = 'the quick brown fox jumps over the lazy dog and keeps running through the vast open fields '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
" > "$TMPDIR_EXHAUST/spec.md"

# Override call_llm to always fail (simulates LLM unavailability)
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_EXHAUST" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ exhaustion returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ exhaustion returns non-zero (got exit 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports failure" "FAILED" "$output"

rm -rf "$TMPDIR_EXHAUST"

# ---------------------------------------------------------------------------
# Test: Lint fails but violations unparseable (Comment 2 regression test)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Lint exit non-zero with unparseable output ==="

TMPDIR_UNPARSE=$(mktemp -d /tmp/mdlint-test-unparse.XXXXXX)

# Create a valid file so the function proceeds past the empty-dir guard
cat > "$TMPDIR_UNPARSE/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Override parse_markdownlint_output to always return empty (simulates
# an unexpected output format that the parser can't handle)
_orig_parse=$(declare -f parse_markdownlint_output)
parse_markdownlint_output() { echo ""; }

# Override npx to simulate lint failure with unparseable output:
# first call (--fix) succeeds, second call (check-only) fails
_npx_call_count=0
npx() {
    _npx_call_count=$((_npx_call_count + 1))
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    echo "some unexpected markdownlint output format"
    return 1
}

call_llm() { return 1; }
MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_UNPARSE" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ unparseable lint failure returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ unparseable lint failure should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports unparseable failure" "FAILED" "$output"

# Restore originals
eval "$_orig_parse"
unset -f npx
unset _npx_call_count

rm -rf "$TMPDIR_UNPARSE"

# ---------------------------------------------------------------------------
# Test: $SPEC_DIR scoping (T025 — files outside spec dir are not modified)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: SPEC_DIR scoping ==="

TMPDIR_SCOPE=$(mktemp -d /tmp/mdlint-test-scope.XXXXXX)
mkdir -p "$TMPDIR_SCOPE/specdir"

# Put a valid file in the spec dir
cat > "$TMPDIR_SCOPE/specdir/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Put a file with violations OUTSIDE spec dir
cat > "$TMPDIR_SCOPE/outside.md" << 'EOF'
no heading at start which is a violation   
EOF

OUTSIDE_BEFORE=$(cat "$TMPDIR_SCOPE/outside.md")

# Override call_llm to avoid actual LLM calls
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=1
run_markdownlint_validation "$TMPDIR_SCOPE/specdir" 2>/dev/null || true

OUTSIDE_AFTER=$(cat "$TMPDIR_SCOPE/outside.md")

assert_eq "outside file unchanged" "$OUTSIDE_BEFORE" "$OUTSIDE_AFTER"

rm -rf "$TMPDIR_SCOPE"

# ---------------------------------------------------------------------------
# Test: MARKDOWNLINT_MAX_ITERATIONS validation (T026)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: MARKDOWNLINT_MAX_ITERATIONS validation ==="

# Self-contained helper that mirrors the validation block in generate-spec-from-issue.sh
_test_validate_iterations() {
    local MARKDOWNLINT_MAX_ITERATIONS="$1"
    if ! [[ "$MARKDOWNLINT_MAX_ITERATIONS" =~ ^[0-9]+$ ]] || (( 10#$MARKDOWNLINT_MAX_ITERATIONS <= 0 )); then
        echo "WARNING"
        MARKDOWNLINT_MAX_ITERATIONS=5
    fi
    echo "$MARKDOWNLINT_MAX_ITERATIONS"
}

# Non-numeric value should fall back to default 5
result=$(_test_validate_iterations "abc")
TESTS_RUN=$((TESTS_RUN + 1))
if echo "$result" | grep -q "WARNING" && echo "$result" | grep -q "^5$"; then
    echo "  ✓ non-numeric value falls back to 5"
    PASS=$((PASS + 1))
else
    echo "  ✗ non-numeric value falls back to 5 (got: $result)"
    FAIL=$((FAIL + 1))
fi

# Zero should fall back to default
result=$(_test_validate_iterations "0")
TESTS_RUN=$((TESTS_RUN + 1))
if echo "$result" | grep -q "WARNING" && echo "$result" | grep -q "^5$"; then
    echo "  ✓ zero falls back to 5"
    PASS=$((PASS + 1))
else
    echo "  ✗ zero falls back to 5 (got: $result)"
    FAIL=$((FAIL + 1))
fi

# Valid positive integer should pass through unchanged
result=$(_test_validate_iterations "3")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$result" == "3" ]]; then
    echo "  ✓ valid value passes through"
    PASS=$((PASS + 1))
else
    echo "  ✗ valid value passes through (got: $result)"
    FAIL=$((FAIL + 1))
fi

# ---------------------------------------------------------------------------
# Test: strip_llm_preamble
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: strip_llm_preamble ==="

# T-preamble-1: No preamble (heading first line) — no-op
input_clean="# My Heading

Some content here."
result=$(strip_llm_preamble "$input_clean" "# My Heading" 2>/dev/null)
assert_eq "no preamble returns as-is" "$input_clean" "$result"

# T-preamble-2: Conversational preamble before heading
input_preamble="All 13 MD013 violations fixed — here is the corrected file:

# My Heading

Some content here."
expected_stripped="# My Heading

Some content here."
result=$(strip_llm_preamble "$input_preamble" "# My Heading" 2>/dev/null)
assert_eq "strips preamble before heading" "$expected_stripped" "$result"

# T-preamble-3: Preamble with original file starting with heading (strategy 1)
input_preamble3="Sure, here is the fixed file:
# Requirements Checklist

- Item 1
- Item 2"
expected3="# Requirements Checklist

- Item 1
- Item 2"
result=$(strip_llm_preamble "$input_preamble3" "# Requirements Checklist" 2>/dev/null)
assert_eq "strips conversational prefix" "$expected3" "$result"

# T-preamble-4: Preamble with list-start (strategy 2, no heading in original)
input_list="Good, I have fixed the violations:
- Item 1
- Item 2"
expected_list="- Item 1
- Item 2"
result=$(strip_llm_preamble "$input_list" "- Item 1" 2>/dev/null)
assert_eq "strips preamble before list" "$expected_list" "$result"

# T-preamble-5: Empty input returns empty
result=$(strip_llm_preamble "" "" 2>/dev/null)
assert_eq "empty input returns empty" "" "$result"

# T-preamble-6: Blockquote start is valid markdown
input_bq="> This is a quote"
result=$(strip_llm_preamble "$input_bq" "> Original" 2>/dev/null)
assert_eq "blockquote is valid md start" "$input_bq" "$result"

# T-preamble-7: Code fence start is valid markdown
input_fence="\`\`\`python
print('hello')
\`\`\`"
result=$(strip_llm_preamble "$input_fence" "\`\`\`python" 2>/dev/null)
assert_eq "code fence is valid md start" "$input_fence" "$result"

# T-preamble-8: Multi-line preamble stripped
input_multi="I have reviewed the file.
All violations have been resolved.
Here is the corrected version:

# Document Title

Content."
expected_multi="# Document Title

Content."
result=$(strip_llm_preamble "$input_multi" "# Document Title" 2>/dev/null)
assert_eq "multi-line preamble stripped" "$expected_multi" "$result"

# T-preamble-9: Warns about preamble on stderr
warn_output=$(strip_llm_preamble "Certainly! Here is the fix:
# Heading" "# Heading" 2>&1 >/dev/null)
assert_contains "logs preamble warning" "preamble detected" "$warn_output"

# T-preamble-10: Leading blank line should not bypass preamble stripping
input_blank_lead="
All violations fixed!
# My Heading

Content."
expected_blank_lead="# My Heading

Content."
result=$(strip_llm_preamble "$input_blank_lead" "# My Heading" 2>/dev/null)
assert_eq "blank first line does not bypass stripping" "$expected_blank_lead" "$result"

# T-preamble-10b: Leading blank lines alone should be trimmed before valid markdown
input_blank_only="
# Heading

Content."
expected_blank_only="# Heading

Content."
result=$(strip_llm_preamble "$input_blank_only" "# Heading" 2>/dev/null)
assert_eq "blank lines before valid markdown are trimmed" "$expected_blank_only" "$result"

# T-preamble-11: h3+ headings are recognised as valid markdown start
input_h3="### Sub Heading

Content."
result=$(strip_llm_preamble "$input_h3" "### Sub Heading" 2>/dev/null)
assert_eq "h3 heading is valid md start" "$input_h3" "$result"

# T-preamble-12: HTML comment start is valid markdown (no preamble — no-op)
input_comment="<!-- markdownlint-disable MD013 -->
# My Heading

Content."
result=$(strip_llm_preamble "$input_comment" "<!-- markdownlint-disable MD013 -->" 2>/dev/null)
assert_eq "HTML comment is valid md start" "$input_comment" "$result"

# T-preamble-13: Preamble before HTML comment is stripped
input_comment_preamble="Sure, here is the corrected file:
<!-- markdownlint-disable MD013 -->
# My Heading

Content."
expected_comment_preamble="<!-- markdownlint-disable MD013 -->
# My Heading

Content."
result=$(strip_llm_preamble "$input_comment_preamble" "<!-- markdownlint-disable MD013 -->" 2>/dev/null)
assert_eq "strips preamble before HTML comment" "$expected_comment_preamble" "$result"

# T-preamble-14: + list marker is valid markdown start (no-op)
input_plus_list="+ Item one
+ Item two"
result=$(strip_llm_preamble "$input_plus_list" "+ Item one" 2>/dev/null)
assert_eq "plus list marker is valid md start" "$input_plus_list" "$result"

# T-preamble-15: Ordered list with space is valid markdown start (no-op)
input_ordered="1. First item
2. Second item"
result=$(strip_llm_preamble "$input_ordered" "1. First item" 2>/dev/null)
assert_eq "ordered list is valid md start" "$input_ordered" "$result"

# T-preamble-16: Dot without trailing space is NOT valid markdown (e.g. version strings)
input_version="2024.04 release notes
# Heading

Content."
expected_version="# Heading

Content."
result=$(strip_llm_preamble "$input_version" "# Heading" 2>/dev/null)
assert_eq "version-like line is not valid md start" "$expected_version" "$result"

# ---------------------------------------------------------------------------
# Test: Violation-count stall detection
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Violation-count stall detection ==="

TMPDIR_COUNTSTALL=$(mktemp -d /tmp/mdlint-test-countstall.XXXXXX)

# Create a file with a violation that auto-fix can't resolve
python3 -c "
print('# Heading')
print()
words = 'the quick brown fox jumps over the lazy dog and keeps running through the vast open fields '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
" > "$TMPDIR_COUNTSTALL/spec.md"

# Stub npx/markdownlint so this test doesn't depend on the real linter.
# First call per iteration is --fix (no-op); second is check-only which
# returns a synthetic violation whose line number shifts each call (so
# fingerprints change) but the violation count stays at 1.
_countstall_npx_file=$(mktemp /tmp/mdlint-countstall-npx.XXXXXX)
echo "0" > "$_countstall_npx_file"
npx() {
    local n
    n=$(cat "$_countstall_npx_file")
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    n=$((n + 1))
    echo "$n" > "$_countstall_npx_file"
    # Emit a synthetic violation at a shifting line number
    local vline=$((10 + n))
    echo "$TMPDIR_COUNTSTALL/spec.md:${vline}:1 MD013/line-length Line length [Expected: 200; Actual: 250]"
    return 1
}

# Override call_llm to return content with violations at *different* line
# numbers each time (so fingerprints change) but the same violation count.
# This simulates the LLM introducing new violations while fixing others.
# We use a file-based counter since call_llm runs in a subshell.
_countstall_file=$(mktemp /tmp/mdlint-countstall-counter.XXXXXX)
echo "0" > "$_countstall_file"
call_llm() {
    local n
    n=$(cat "$_countstall_file")
    n=$((n + 1))
    echo "$n" > "$_countstall_file"
    python3 -c "
print('# Heading')
print()
# Add varying short paragraphs so the long line ends up on different lines
for i in range($n + 1):
    print('Short paragraph ' + str(i) + '.')
    print()
words = 'different long text that exceeds the line length limit by a lot because we keep adding more words '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
"
}

MARKDOWNLINT_MAX_ITERATIONS=5
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_COUNTSTALL" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ count-stall returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ count-stall should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports stall in output" "Stall detected" "$output"

# Should not exhaust all 5 iterations — stall should trigger earlier
assert_contains "exits before max iterations" "violation count has not decreased" "$output"

unset -f npx
rm -rf "$TMPDIR_COUNTSTALL"
rm -f "$_countstall_file"
rm -f "$_countstall_npx_file"

# ---------------------------------------------------------------------------
# Test: Whitespace-only LLM output should not overwrite file
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Whitespace-only LLM output guard ==="

TMPDIR_WSGUARD=$(mktemp -d /tmp/mdlint-test-wsguard.XXXXXX)

# Create a markdown file with a violation
printf '# Heading\n\n%s\n' "$(printf '%0.sX' {1..250})" > "$TMPDIR_WSGUARD/spec.md"
original_content=$(cat "$TMPDIR_WSGUARD/spec.md")

# Stub npx: first call (--fix) is no-op, second (check-only) reports a violation,
# subsequent calls report clean so the loop terminates.
_wsguard_npx_file=$(mktemp /tmp/mdlint-wsguard-npx.XXXXXX)
echo "0" > "$_wsguard_npx_file"
npx() {
    local n
    n=$(cat "$_wsguard_npx_file")
    n=$((n + 1))
    echo "$n" > "$_wsguard_npx_file"
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    if [[ $n -le 2 ]]; then
        echo "$TMPDIR_WSGUARD/spec.md:3:1 MD013/line-length Line length [Expected: 200; Actual: 250]"
        return 1
    fi
    return 0
}

# Override call_llm to return whitespace-only content
call_llm() {
    printf '\n   \n\n'
}

MARKDOWNLINT_MAX_ITERATIONS=3
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_WSGUARD" 2>&1) || exit_code=$?

assert_contains "logs whitespace-only warning" "blank or whitespace-only" "$output"

# Verify original file content was preserved (not overwritten with whitespace)
current_content=$(cat "$TMPDIR_WSGUARD/spec.md")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$current_content" == "$original_content" ]]; then
    echo "  ✓ file not overwritten with whitespace-only content"
    PASS=$((PASS + 1))
else
    echo "  ✗ file was overwritten despite whitespace-only LLM output"
    FAIL=$((FAIL + 1))
fi

unset -f npx
rm -rf "$TMPDIR_WSGUARD"
rm -f "$_wsguard_npx_file"

# ---------------------------------------------------------------------------
# Test: ensure_heading_start
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: ensure_heading_start ==="

# T-heading-1: Content already starting with a heading — returned unchanged
input_h1="# My Document

Some content."
result=$(ensure_heading_start "$input_h1" "# Default Heading" 2>/dev/null)
assert_eq "heading already present returns unchanged" "$input_h1" "$result"

# T-heading-2: Content starting with plain text — default heading prepended
input_plain="Some plain text without a heading.

More content."
expected_plain="# Default Heading

Some plain text without a heading.

More content."
result=$(ensure_heading_start "$input_plain" "# Default Heading" 2>/dev/null)
assert_eq "plain text gets heading prepended" "$expected_plain" "$result"

# T-heading-3: Content starting with blank lines then a heading — blanks stripped, heading preserved
input_blank_heading="

# My Heading

Content."
expected_blank_heading="# My Heading

Content."
result=$(ensure_heading_start "$input_blank_heading" "# Default Heading" 2>/dev/null)
assert_eq "blank lines then heading strips blanks" "$expected_blank_heading" "$result"

# T-heading-4: Content starting with blank lines then plain text — default heading prepended
input_blank_plain="

Some text without heading."
expected_blank_plain="# Default Heading

Some text without heading."
result=$(ensure_heading_start "$input_blank_plain" "# Default Heading" 2>/dev/null)
assert_eq "blank lines then plain text gets heading" "$expected_blank_plain" "$result"

# T-heading-5: Empty content — default heading returned
result=$(ensure_heading_start "" "# Default Heading" 2>/dev/null)
assert_eq "empty content returns default heading" "# Default Heading" "$result"

# T-heading-6: Content starting with h2 — treated as valid heading
input_h2="## Sub Heading

Content."
result=$(ensure_heading_start "$input_h2" "# Default Heading" 2>/dev/null)
assert_eq "h2 heading is valid" "$input_h2" "$result"

# T-heading-7: Warns when heading is prepended
warn_output=$({ ensure_heading_start "No heading here" "# Default Heading" >/dev/null; } 2>&1)
assert_contains "logs heading prepend warning" "No heading found" "$warn_output"

# ---------------------------------------------------------------------------
# Test: quick_markdown_sanity_check
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: quick_markdown_sanity_check ==="

TMPDIR_SANITY=$(mktemp -d /tmp/mdlint-test-sanity.XXXXXX)

# Create test fixtures
# (a) File with leading blank lines
printf '\n\n# Heading\n\nContent.\n' > "$TMPDIR_SANITY/leading-blanks.md"

# (b) Empty file
touch "$TMPDIR_SANITY/empty.md"

# (c) File starting with code fence
printf '```python\nprint("hello")\n```\n' > "$TMPDIR_SANITY/code-fence.md"

# (d) File with no heading (plain text)
printf 'Just some text.\n' > "$TMPDIR_SANITY/no-heading.md"

# (e) Valid file (control)
printf '# Valid Heading\n\nContent.\n' > "$TMPDIR_SANITY/valid.md"

# (f) Whitespace-only file (non-zero bytes but no real content)
printf '   \n\t\n  \n' > "$TMPDIR_SANITY/whitespace-only.md"

# Save originals for comparison
code_fence_original=$(cat "$TMPDIR_SANITY/code-fence.md")

# Run sanity check
sanity_output=$(quick_markdown_sanity_check "$TMPDIR_SANITY" 2>&1)

# Verify leading blanks are removed
leading_blanks_content=$(cat "$TMPDIR_SANITY/leading-blanks.md")
expected_leading_blanks="# Heading

Content."
assert_eq "leading blanks removed" "$expected_leading_blanks" "$leading_blanks_content"

# Verify empty file is still empty (skipped)
TESTS_RUN=$((TESTS_RUN + 1))
if [[ ! -s "$TMPDIR_SANITY/empty.md" ]]; then
    echo "  ✓ empty file skipped (still empty)"
    PASS=$((PASS + 1))
else
    echo "  ✗ empty file should still be empty"
    FAIL=$((FAIL + 1))
fi

# Verify whitespace-only file is truncated to empty
TESTS_RUN=$((TESTS_RUN + 1))
if [[ ! -s "$TMPDIR_SANITY/whitespace-only.md" ]]; then
    echo "  ✓ whitespace-only file truncated to empty"
    PASS=$((PASS + 1))
else
    echo "  ✗ whitespace-only file should be truncated to empty"
    FAIL=$((FAIL + 1))
fi

# Verify code fence file is unchanged
code_fence_content=$(cat "$TMPDIR_SANITY/code-fence.md")
assert_eq "code fence file unchanged" "$code_fence_original" "$code_fence_content"

# Verify warnings were logged
assert_contains "warns about empty file" "Empty file" "$sanity_output"
assert_contains "warns about whitespace-only file" "Empty/blank file" "$sanity_output"
assert_contains "warns about code fence" "code fence" "$sanity_output"
assert_contains "warns about no heading" "does not start with a heading" "$sanity_output"

# Verify valid file is unchanged
valid_content=$(cat "$TMPDIR_SANITY/valid.md")
expected_valid="# Valid Heading

Content."
assert_eq "valid file unchanged" "$expected_valid" "$valid_content"

# Verify function always returns 0
exit_code=0
quick_markdown_sanity_check "$TMPDIR_SANITY" 2>/dev/null || exit_code=$?
assert_eq "sanity check returns 0" "0" "$exit_code"

rm -rf "$TMPDIR_SANITY"

# ---------------------------------------------------------------------------
# Test: _join_continuation_lines
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: _join_continuation_lines ==="

# T-join-1: Single-line violation passes through unchanged
input_single="specs/test/spec.md:1:1 error MD041/first-line-heading First line should be a heading"
result=$(_join_continuation_lines "$input_single")
assert_eq "single-line passthrough" "$input_single" "$result"

# T-join-2: Two-line violation (one continuation) joined into one line
input_two=$'specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1\nFirst line in a file should be a top-level heading [Context: "Spec created at ..."]'
result=$(_join_continuation_lines "$input_two")
expected_two='specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "Spec created at ..."]'
assert_eq "two-line join" "$expected_two" "$result"
count=$(printf '%s\n' "$result" | wc -l | tr -d ' ')
assert_eq "two-line join produces 1 line" "1" "$count"

# T-join-3: Three-line violation (two continuations) joined into one line
input_three=$'specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1\nFirst line in a file should be\na top-level heading [Context: "Spec created at ..."]'
result=$(_join_continuation_lines "$input_three")
expected_three='specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "Spec created at ..."]'
assert_eq "three-line join" "$expected_three" "$result"
count=$(printf '%s\n' "$result" | wc -l | tr -d ' ')
assert_eq "three-line join produces 1 line" "1" "$count"

# T-join-4: Multiple violations with mixed wrapping
input_mixed=$'file1.md:1:1 error MD041/first-line-heading First line\nfile2.md:50:81 error MD013/line-length\nLine length 205 > 200\nfile3.md:10:1 error MD040/fenced-code-language Fenced code blocks should have a language'
result=$(_join_continuation_lines "$input_mixed")
count=$(printf '%s\n' "$result" | wc -l | tr -d ' ')
assert_eq "mixed wrapping produces 3 lines" "3" "$count"
assert_contains "first violation present" "file1.md:1:1" "$result"
assert_contains "second violation joined" "Line length 205 > 200" "$result"
assert_contains "third violation present" "file3.md:10:1" "$result"
# Verify rule and description are on the same line for the joined violation
second_line=$(printf '%s\n' "$result" | grep "file2.md")
assert_contains "second line has rule and desc together" "MD013/line-length" "$second_line"
assert_contains "second line has joined description" "Line length 205 > 200" "$second_line"

# T-join-5: Empty input returns nothing
result=$(_join_continuation_lines "")
assert_eq "empty input returns empty" "" "$result"

# T-join-6: Metadata/footer lines are treated as boundaries, not appended
input_meta=$'specs/test/spec.md:1 error MD041/first-line-heading First line\nmarkdownlint-cli2 v0.22.0\nFinding: 1 file(s)\nLinting: 1 file(s)\nSummary: 1 error(s)'
result=$(_join_continuation_lines "$input_meta")
count=$(printf '%s\n' "$result" | wc -l | tr -d ' ')
assert_eq "metadata boundary produces 1 line" "1" "$count"
# Verify that metadata lines are NOT appended to the violation
first_line=$(printf '%s\n' "$result" | head -1)
assert_eq "metadata not appended to violation" "specs/test/spec.md:1 error MD041/first-line-heading First line" "$first_line"

# T-join-7: Blank lines act as boundaries between violations
input_blanks=$'file1.md:1 error MD041/first-line-heading First line\n\nfile2.md:10 error MD013/line-length Line too long'
result=$(_join_continuation_lines "$input_blanks")
count=$(printf '%s\n' "$result" | wc -l | tr -d ' ')
assert_eq "blank separator produces 2 lines" "2" "$count"

# ---------------------------------------------------------------------------
# Test: _count_raw_violations
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: _count_raw_violations ==="

# T-count-1: Input with 2 violation-start lines
input_count=$'specs/test/spec.md:1 error MD041/first-line-heading First line\nspecs/test/spec.md:50:81 error MD013/line-length Line length'
result=$(_count_raw_violations "$input_count")
assert_eq "counts 2 violations" "2" "$result"

# T-count-2: Empty input
result=$(_count_raw_violations "")
assert_eq "empty input returns 0" "0" "$result"

# T-count-3: Input with metadata-only lines (no filename:line pattern)
input_meta=$'markdownlint-cli2 v0.22.0\nFinding: some files\nLinting: 1 file(s)\nSummary: 0 error(s)'
result=$(_count_raw_violations "$input_meta")
assert_eq "metadata-only returns 0" "0" "$result"

# ---------------------------------------------------------------------------
# Test: parse_markdownlint_output with three-segment rule names
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Three-segment rule names ==="

output=$(parse_markdownlint_output "specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1 First line should be a heading")
assert_contains "three-segment rule parsed" "MD041/first-line-heading/first-line-h1" "$output"

# ---------------------------------------------------------------------------
# Test: parse_markdownlint_output with wrapped [Context: ...] descriptions
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Wrapped Context descriptions ==="

# Two-line input: violation start + continuation with [Context: ...]
input_wrapped=$'specs/test/spec.md:1 error MD041/first-line-heading/first-line-h1\nFirst line in a file should be a top-level heading [Context: "Spec created at ..."]'
output=$(parse_markdownlint_output "$input_wrapped")
count=$(printf '%s\n' "$output" | awk 'NF' | wc -l | tr -d ' ')
assert_eq "wrapped context returns 1 violation" "1" "$count"
assert_contains "wrapped rule is correct" "MD041/first-line-heading/first-line-h1" "$output"
assert_contains "wrapped description contains text" "First line in a file should be" "$output"

# ---------------------------------------------------------------------------
# Test: Mixed single-line and multi-line violations
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Mixed single-line and multi-line violations ==="

input_mix=$'file1.md:1:1 error MD041/first-line-heading/first-line-h1 First line should be a heading
file2.md:50:81 error MD013/line-length
Line length 205 > 200 [Expected: 200; Actual: 205]
file3.md:10:1 error MD040/fenced-code-language Fenced code blocks should have a language specified'
output=$(parse_markdownlint_output "$input_mix")
count=$(printf '%s\n' "$output" | awk 'NF' | wc -l | tr -d ' ')
assert_eq "mixed violations returns 3" "3" "$count"
assert_contains "first single-line violation" "MD041/first-line-heading/first-line-h1" "$output"
assert_contains "second multi-line violation" "MD013/line-length" "$output"
assert_contains "second violation description joined" "Line length 205 > 200" "$output"
assert_contains "third single-line violation" "MD040/fenced-code-language" "$output"

# ---------------------------------------------------------------------------
# Test: Raw-remediation fallback path
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Raw-remediation fallback path ==="

TMPDIR_RAWFALLBACK=$(mktemp -d /tmp/mdlint-test-rawfallback.XXXXXX)

# Create a valid file so the function proceeds past the empty-dir guard
cat > "$TMPDIR_RAWFALLBACK/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Override parse_markdownlint_output to always return empty (simulates
# an output format that the parser can't handle)
_orig_parse_raw=$(declare -f parse_markdownlint_output)
parse_markdownlint_output() { echo ""; }

# Override npx: --fix is no-op; check-only returns non-zero with synthetic
# output on the first call pair, then returns 0 on the second check-only
# (simulating that the LLM raw remediation fixed the issue).
_rawfb_npx_file=$(mktemp /tmp/mdlint-rawfb-npx.XXXXXX)
echo "0" > "$_rawfb_npx_file"
npx() {
    local n
    n=$(cat "$_rawfb_npx_file")
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    n=$((n + 1))
    echo "$n" > "$_rawfb_npx_file"
    if [[ $n -le 1 ]]; then
        echo "$TMPDIR_RAWFALLBACK/spec.md:1 error MD041/first-line-heading/first-line-h1"
        echo "First line in a file should be a top-level heading"
        return 1
    fi
    return 0
}

# Override call_llm to return corrected content
call_llm() {
    echo "# Valid Spec

Content here."
}

MARKDOWNLINT_MAX_ITERATIONS=3
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_RAWFALLBACK" 2>&1) || exit_code=$?

assert_eq "raw fallback returns success" "0" "$exit_code"
assert_contains "logs raw remediation attempt" "Attempting raw-output LLM remediation" "$output"
assert_contains "logs raw remediation applied" "Raw LLM remediation applied" "$output"
assert_contains "reports success after raw remediation" "SUCCESS" "$output"

# Restore originals
eval "$_orig_parse_raw"
unset -f npx
unset -f call_llm
rm -f "$_rawfb_npx_file"
rm -rf "$TMPDIR_RAWFALLBACK"

# ---------------------------------------------------------------------------
# Test: Raw-remediation fallback — all LLM calls fail → break
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Raw-remediation fallback (all fail) ==="

TMPDIR_RAWFAIL=$(mktemp -d /tmp/mdlint-test-rawfail.XXXXXX)

cat > "$TMPDIR_RAWFAIL/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

_orig_parse_rawfail=$(declare -f parse_markdownlint_output)
parse_markdownlint_output() { echo ""; }

npx() {
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    echo "some unexpected markdownlint output format"
    return 1
}

call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_RAWFAIL" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ raw fallback all-fail returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ raw fallback all-fail should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "logs raw remediation attempt on fail" "Attempting raw-output LLM remediation" "$output"
assert_contains "logs raw remediation failed" "Raw remediation failed for all files" "$output"
assert_contains "reports failure" "FAILED" "$output"

eval "$_orig_parse_rawfail"
unset -f npx
unset -f call_llm
rm -rf "$TMPDIR_RAWFAIL"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "======================================="
echo "Tests: $TESTS_RUN  Passed: $PASS  Failed: $FAIL"
echo "======================================="

if [[ $FAIL -gt 0 ]]; then
    exit 1
fi
exit 0
