#!/usr/bin/env bash
#
# test_content_preservation.sh - Tests for content preservation functions
#
# Exercises the backup, counting, validation, and safe-write functions added
# to generate-spec-from-issue.sh for the content-preserving augmentation fix
# (issue #1195).
#
# Usage: bash test_content_preservation.sh
#
# Exit code: 0 if all tests pass, 1 if any fail.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PASS=0
FAIL=0
TESTS_RUN=0

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------
assert_eq() {
    local test_name="$1" expected="$2" actual="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$expected" == "$actual" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected: $expected"
        echo "    actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local test_name="$1" needle="$2" haystack="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$haystack" | grep -qF "$needle"; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected to contain: $needle"
        echo "    actual: $haystack"
        FAIL=$((FAIL + 1))
    fi
}

assert_file_exists() {
    local test_name="$1" filepath="$2"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ -f "$filepath" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected file to exist: $filepath"
        FAIL=$((FAIL + 1))
    fi
}

assert_file_not_exists() {
    local test_name="$1" filepath="$2"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ ! -f "$filepath" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected file NOT to exist: $filepath"
        FAIL=$((FAIL + 1))
    fi
}

assert_exit_code() {
    local test_name="$1" expected_code="$2"
    shift 2
    TESTS_RUN=$((TESTS_RUN + 1))
    local actual_code=0
    "$@" 2>/dev/null || actual_code=$?
    if [[ $actual_code -eq $expected_code ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected exit code: $expected_code"
        echo "    actual exit code:   $actual_code"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# Source the content preservation functions from the main script using sed.
# Extract from the Content Preservation section marker to the Phase Functions
# marker.
# ---------------------------------------------------------------------------
COPILOT_MODEL="${COPILOT_MODEL:-test-model}"

# We need helper functions that the content preservation functions depend on
_strip_footer_from_text() {
    local text="$1"
    printf '%s' "$text" | sed -E ':a;N;$!ba;s/\n*\n---\n\*Generated by Copilot SDK \([^)]*\)\*[[:space:]]*$//'
}

strip_model_footer() {
    _strip_footer_from_text "$1"
}

append_model_footer() {
    local file="$1"
    local content
    content=$(_strip_footer_from_text "$(cat "$file")")
    printf '%s' "$content" > "$file"
    printf '\n\n---\n*Generated by Copilot SDK (%s)*\n' "$COPILOT_MODEL" >> "$file"
}

_extracted_cp_functions=$(sed -n '/^# ========================== Content Preservation/,/^# ========================== Phase Functions/p' "$SCRIPT_DIR/generate-spec-from-issue.sh" | head -n -1)

# Source the extracted function definitions
# shellcheck disable=SC1090
source /dev/stdin <<< "$_extracted_cp_functions"

# ---------------------------------------------------------------------------
# Temp directory for test artifacts
# ---------------------------------------------------------------------------
TEST_TMPDIR=""
setup_tmpdir() {
    TEST_TMPDIR=$(mktemp -d)
}
teardown_tmpdir() {
    [[ -n "$TEST_TMPDIR" ]] && rm -rf "$TEST_TMPDIR"
}

# Fixture paths
FIXTURE_DIR="$SCRIPT_DIR/fixtures/content-preservation"
FIXTURE_SPEC="$FIXTURE_DIR/spec.md"
FIXTURE_CHECKLIST="$FIXTURE_DIR/checklists/requirements.md"

# ---------------------------------------------------------------------------
# Test: create_backup
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: create_backup ==="

setup_tmpdir

# T1: Creates .bak file with correct content
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/spec.md"
backup_path=$(create_backup "$TEST_TMPDIR/spec.md")
assert_eq "creates .bak file" "$TEST_TMPDIR/spec.md.bak" "$backup_path"
assert_file_exists "backup file exists" "$backup_path"
assert_eq "backup content matches" "$(cat "$FIXTURE_SPEC")" "$(cat "$backup_path")"

# T2: Uses .bak.1 suffix on collision
backup_path2=$(create_backup "$TEST_TMPDIR/spec.md")
assert_eq "uses .bak.1 on collision" "$TEST_TMPDIR/spec.md.bak.1" "$backup_path2"
assert_file_exists "second backup exists" "$backup_path2"

# T3: Uses .bak.2 on subsequent collision
backup_path3=$(create_backup "$TEST_TMPDIR/spec.md")
assert_eq "uses .bak.2 on collision" "$TEST_TMPDIR/spec.md.bak.2" "$backup_path3"

# T4: Returns non-zero on write failure (read-only directory)
mkdir -p "$TEST_TMPDIR/readonly"
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/readonly/spec.md"
chmod 555 "$TEST_TMPDIR/readonly"
assert_exit_code "fails on read-only directory" 1 create_backup "$TEST_TMPDIR/readonly/spec.md"
chmod 755 "$TEST_TMPDIR/readonly"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: restore_from_backup
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: restore_from_backup ==="

setup_tmpdir

# T5: Restores original from backup
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/spec.md.bak"
echo "modified content" > "$TEST_TMPDIR/spec.md"
restore_from_backup "$TEST_TMPDIR/spec.md" "$TEST_TMPDIR/spec.md.bak"
assert_eq "restores original content" "$(cat "$FIXTURE_SPEC")" "$(cat "$TEST_TMPDIR/spec.md")"

# T6: Fails when backup is missing
assert_exit_code "fails when backup missing" 1 restore_from_backup "$TEST_TMPDIR/spec.md" "$TEST_TMPDIR/nonexistent.bak"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: count_requirement_entries
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: count_requirement_entries ==="

setup_tmpdir

# T7: Counts FR and NFR entries correctly
count=$(count_requirement_entries "$FIXTURE_SPEC")
assert_eq "counts 15 requirement entries" "15" "$count"

# T8: Returns 0 for file with no requirements
echo "No requirements here." > "$TEST_TMPDIR/empty.md"
count=$(count_requirement_entries "$TEST_TMPDIR/empty.md")
assert_eq "returns 0 for no requirements" "0" "$count"

# T9: Ignores non-requirement bullets
cat > "$TEST_TMPDIR/mixed.md" << 'EOF'
- **FR-001**: A real requirement
- **NFR-001**: Another real requirement
- Regular bullet point
- **NOTFR-001**: Not a requirement
## Requirements heading (not a requirement)
EOF
count=$(count_requirement_entries "$TEST_TMPDIR/mixed.md")
assert_eq "ignores non-requirement bullets" "2" "$count"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: count_checklist_items
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: count_checklist_items ==="

setup_tmpdir

# T10: Counts checklist items correctly (fixture has 10 items)
count=$(count_checklist_items "$FIXTURE_CHECKLIST")
assert_eq "counts 10 checklist items" "10" "$count"

# T11: Returns 0 for empty file
echo "" > "$TEST_TMPDIR/empty.md"
count=$(count_checklist_items "$TEST_TMPDIR/empty.md")
assert_eq "returns 0 for empty file" "0" "$count"

# T12: Ignores plain bullets
cat > "$TEST_TMPDIR/mixed.md" << 'EOF'
- [ ] Unchecked item
- [x] Checked lowercase
- [X] Checked uppercase
- Regular bullet
- Another regular bullet
EOF
count=$(count_checklist_items "$TEST_TMPDIR/mixed.md")
assert_eq "counts only task list items" "3" "$count"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: extract_section_headings
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: extract_section_headings ==="

setup_tmpdir

# T13: Extracts ## headings
headings=$(extract_section_headings "$FIXTURE_SPEC")
assert_contains "extracts Problem Statement" "## Problem Statement" "$headings"
assert_contains "extracts Requirements" "## Requirements" "$headings"
assert_contains "extracts Success Criteria" "## Success Criteria" "$headings"

# T14: Strips *(mandatory)* annotations
assert_contains "strips mandatory from User Scenarios" "## User Scenarios & Testing" "$headings"
assert_contains "strips mandatory from Requirements" "## Requirements" "$headings"

# T15: Trims whitespace
# Each heading line should not end with trailing spaces
while IFS= read -r h; do
    [[ -z "$h" ]] && continue
    trimmed=$(echo "$h" | sed 's/[[:space:]]*$//')
    assert_eq "heading has no trailing whitespace: '$h'" "$trimmed" "$h"
    break  # Just test the first one
done <<< "$headings"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: validate_structural_integrity
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: validate_structural_integrity ==="

setup_tmpdir

# T16: Passes when all sections retained and counts match
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/original.md"
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/candidate.md"
assert_exit_code "passes with identical files" 0 validate_structural_integrity "$TEST_TMPDIR/original.md" "$TEST_TMPDIR/candidate.md" --type spec

# T17: Fails when mandatory section missing
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/original.md"
grep -v "^## Problem Statement" "$FIXTURE_SPEC" > "$TEST_TMPDIR/bad_candidate.md"
assert_exit_code "fails when mandatory section missing" 1 validate_structural_integrity "$TEST_TMPDIR/original.md" "$TEST_TMPDIR/bad_candidate.md" --type spec

# T18: Fails when original section heading missing
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/original.md"
grep -v "^## Edge Cases" "$FIXTURE_SPEC" > "$TEST_TMPDIR/missing_section.md"
assert_exit_code "fails when original heading missing" 1 validate_structural_integrity "$TEST_TMPDIR/original.md" "$TEST_TMPDIR/missing_section.md" --type spec

# T19: Fails when requirement count drops below 95%
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/original.md"
# Remove 4 of 15 requirements (keep 11 = 73%, below 95% threshold)
sed '/\*\*FR-005\*\*/d; /\*\*FR-006\*\*/d; /\*\*FR-007\*\*/d; /\*\*FR-008\*\*/d' "$FIXTURE_SPEC" > "$TEST_TMPDIR/truncated.md"
assert_exit_code "fails when requirement count drops below 95%" 1 validate_structural_integrity "$TEST_TMPDIR/original.md" "$TEST_TMPDIR/truncated.md" --type spec

# T20: Passes when original has 0 requirements
cat > "$TEST_TMPDIR/no_reqs_orig.md" << 'EOF'
## Problem Statement

No requirements here.

## User Scenarios & Testing

None.

## Requirements

No formal requirements.

## Success Criteria

None.
EOF
cp "$TEST_TMPDIR/no_reqs_orig.md" "$TEST_TMPDIR/no_reqs_candidate.md"
assert_exit_code "passes with 0 requirements" 0 validate_structural_integrity "$TEST_TMPDIR/no_reqs_orig.md" "$TEST_TMPDIR/no_reqs_candidate.md" --type spec

# T21: Strips *(mandatory)* annotations before matching
cat > "$TEST_TMPDIR/annotated_orig.md" << 'EOF'
## Problem Statement

Content.

## User Scenarios & Testing *(mandatory)*

Content.

## Requirements *(mandatory)*

- **FR-001**: Something

## Success Criteria *(mandatory)*

Content.
EOF
# Candidate without annotations but same headings
cat > "$TEST_TMPDIR/annotated_candidate.md" << 'EOF'
## Problem Statement

Content.

## User Scenarios & Testing

Content.

## Requirements

- **FR-001**: Something

## Success Criteria

Content.
EOF
assert_exit_code "handles mandatory annotations" 0 validate_structural_integrity "$TEST_TMPDIR/annotated_orig.md" "$TEST_TMPDIR/annotated_candidate.md" --type spec

# T22: Checklist type - passes with all items retained
cp "$FIXTURE_CHECKLIST" "$TEST_TMPDIR/orig_checklist.md"
cp "$FIXTURE_CHECKLIST" "$TEST_TMPDIR/candidate_checklist.md"
assert_exit_code "checklist: passes with all items" 0 validate_structural_integrity "$TEST_TMPDIR/orig_checklist.md" "$TEST_TMPDIR/candidate_checklist.md" --type checklist

# T23: Checklist type - fails when items are lost
cp "$FIXTURE_CHECKLIST" "$TEST_TMPDIR/orig_checklist.md"
# Remove 3 checklist items
head -12 "$FIXTURE_CHECKLIST" > "$TEST_TMPDIR/truncated_checklist.md"
assert_exit_code "checklist: fails when items lost" 1 validate_structural_integrity "$TEST_TMPDIR/orig_checklist.md" "$TEST_TMPDIR/truncated_checklist.md" --type checklist

teardown_tmpdir

# ---------------------------------------------------------------------------
# Test: safe_write_with_validation
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: safe_write_with_validation ==="

setup_tmpdir

# T24: Successful write replaces original with backup retained
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/spec.md"
original_content=$(cat "$TEST_TMPDIR/spec.md")
# Create a valid candidate (same content + a small addition)
candidate_content="${original_content}

## Additional Notes

This was added by the clarification step.
"
assert_exit_code "successful write passes" 0 safe_write_with_validation "$TEST_TMPDIR/spec.md" "$candidate_content" --type spec
assert_file_exists "backup retained after success" "$TEST_TMPDIR/spec.md.bak"
assert_file_not_exists "tmp cleaned up after success" "$TEST_TMPDIR/spec.md.tmp"
assert_contains "new content present" "Additional Notes" "$(cat "$TEST_TMPDIR/spec.md")"

# T25: Failed validation leaves original unchanged
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/spec2.md"
truncated_content="# Truncated Spec

## Problem Statement

Just a summary.
"
assert_exit_code "failed validation returns 1" 1 safe_write_with_validation "$TEST_TMPDIR/spec2.md" "$truncated_content" --type spec
assert_eq "original unchanged after failed validation" "$(cat "$FIXTURE_SPEC")" "$(cat "$TEST_TMPDIR/spec2.md")"
assert_file_exists "backup exists after failed validation" "$TEST_TMPDIR/spec2.md.bak"
assert_file_not_exists "tmp cleaned up after failed validation" "$TEST_TMPDIR/spec2.md.tmp"

# T26: Backup write failure aborts without touching original
mkdir -p "$TEST_TMPDIR/readonly2"
cp "$FIXTURE_SPEC" "$TEST_TMPDIR/readonly2/spec.md"
chmod 555 "$TEST_TMPDIR/readonly2"
assert_exit_code "backup failure aborts" 1 safe_write_with_validation "$TEST_TMPDIR/readonly2/spec.md" "anything" --type spec
assert_eq "original unchanged on backup failure" "$(cat "$FIXTURE_SPEC")" "$(cat "$TEST_TMPDIR/readonly2/spec.md")"
chmod 755 "$TEST_TMPDIR/readonly2"

teardown_tmpdir

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== Results: $TESTS_RUN tests | $PASS passed | $FAIL failed ==="

if [[ "$FAIL" -gt 0 ]]; then
    echo "❌ CONTENT PRESERVATION TESTS FAILED"
    exit 1
else
    echo "✅ CONTENT PRESERVATION TESTS PASSED"
    exit 0
fi
