#!/usr/bin/env bash
#
# test_markdownlint_validation.sh - Tests for the markdownlint validation loop
#
# Exercises the helper functions and validation flow added to
# generate-spec-from-issue.sh for Phase 7 (markdownlint validation).
#
# Usage: bash test_markdownlint_validation.sh
#
# Prerequisites: npx, markdownlint-cli2

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

PASS=0
FAIL=0
TESTS_RUN=0

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------
assert_eq() {
    local test_name="$1" expected="$2" actual="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ "$expected" == "$actual" ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected: $expected"
        echo "    actual:   $actual"
        FAIL=$((FAIL + 1))
    fi
}

assert_contains() {
    local test_name="$1" needle="$2" haystack="$3"
    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$haystack" | grep -qF "$needle"; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected to contain: $needle"
        echo "    actual: $haystack"
        FAIL=$((FAIL + 1))
    fi
}

assert_exit_code() {
    local test_name="$1" expected_code="$2"
    shift 2
    TESTS_RUN=$((TESTS_RUN + 1))
    local actual_code=0
    "$@" || actual_code=$?
    if [[ $actual_code -eq $expected_code ]]; then
        echo "  ✓ $test_name"
        PASS=$((PASS + 1))
    else
        echo "  ✗ $test_name"
        echo "    expected exit code: $expected_code"
        echo "    actual exit code:   $actual_code"
        FAIL=$((FAIL + 1))
    fi
}

# ---------------------------------------------------------------------------
# Source the functions under test.
#
# We need the markdownlint validation helpers from generate-spec-from-issue.sh.
# To avoid running the main script body (which requires env vars and runs the
# full pipeline), we extract just the function definitions between known
# section markers.  This is safe because both files are in the same repo and
# the markers are stable section headers maintained by the same team.
# ---------------------------------------------------------------------------

# We need these vars to be set for the helper functions.
COPILOT_MODEL="${COPILOT_MODEL:-test-model}"
MARKDOWNLINT_PROMPT_MAX_CHARS=32000

# Footer management functions (duplicated here to avoid sourcing the full script)
_strip_footer_from_text() {
    local text="$1"
    printf '%s' "$text" | sed -E ':a;N;$!ba;s/\n*\n---\n\*Generated by Copilot SDK \([^)]*\)\*[[:space:]]*$//'
}

strip_model_footer() {
    _strip_footer_from_text "$1"
}

append_model_footer() {
    local file="$1"
    local content
    content=$(_strip_footer_from_text "$(cat "$file")")
    printf '%s' "$content" > "$file"
    printf '\n\n---\n*Generated by Copilot SDK (%s)*\n' "$COPILOT_MODEL" >> "$file"
}

# Extract markdownlint validation functions from the main script using sed.
# This reads the section between the "Markdownlint Validation" and "Phase
# Functions" markers and sources it directly.
_extracted_functions=$(sed -n '/^# ========================== Markdownlint Validation/,/^# ========================== Phase Functions/p' "$SCRIPT_DIR/generate-spec-from-issue.sh" | head -n -1)

# Source the extracted function definitions
source /dev/stdin <<< "$_extracted_functions"

# ---------------------------------------------------------------------------
# Test: parse_markdownlint_output
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: parse_markdownlint_output ==="

# T1: Standard violation format with column and error keyword (v0.22+)
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 error MD041/first-line-heading First line should be a heading")
assert_contains "parses filename" "specs/test/spec.md" "$output"
assert_contains "parses line number" "10" "$output"
assert_contains "parses rule" "MD041/first-line-heading" "$output"

# T2: Empty input
output=$(parse_markdownlint_output "")
assert_eq "empty input returns empty" "" "$output"

# T3: Multiple violations (with error keyword)
input="file1.md:1:1 error MD041/first-line-heading First line should be a heading
file2.md:50:81 error MD013/line-length Line length 205 > 200"
output=$(parse_markdownlint_output "$input")
count=$(printf '%s\n' "$output" | awk 'END{print NR}')
assert_eq "parses multiple violations" "2" "$count"

# T3b: Legacy format without error keyword
output=$(parse_markdownlint_output "specs/test/spec.md:10:1 MD041/first-line-heading First line should be a heading")
assert_contains "parses legacy format" "MD041/first-line-heading" "$output"

# ---------------------------------------------------------------------------
# Test: compute_violation_fingerprint
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: compute_violation_fingerprint ==="

# T4: Empty violations
fp=$(compute_violation_fingerprint "")
assert_eq "empty violations fingerprint" "empty" "$fp"

# T5: Same violations produce same fingerprint
violations="file.md	10	1	MD041/first-line-heading	First line should be heading"
fp1=$(compute_violation_fingerprint "$violations")
fp2=$(compute_violation_fingerprint "$violations")
assert_eq "deterministic fingerprint" "$fp1" "$fp2"

# T6: Different violations produce different fingerprints
violations2="file.md	20	1	MD013/line-length	Line too long"
fp3=$(compute_violation_fingerprint "$violations2")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$fp1" != "$fp3" ]]; then
    echo "  ✓ different violations give different fingerprints"
    PASS=$((PASS + 1))
else
    echo "  ✗ different violations give different fingerprints"
    FAIL=$((FAIL + 1))
fi

# ---------------------------------------------------------------------------
# Test: check_npx_available
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: check_npx_available ==="

# T7: npx should be available in CI
assert_exit_code "npx is available" 0 check_npx_available

# ---------------------------------------------------------------------------
# Test: Auto-fix path (T006 — auto-fixable violations resolved without LLM)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Auto-fix path ==="

TMPDIR_TEST=$(mktemp -d /tmp/mdlint-test-autofix.XXXXXX)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# Create a file with trailing spaces (auto-fixable by markdownlint --fix)
cat > "$TMPDIR_TEST/test.md" << 'EOF'
# Test Document

This line has trailing spaces   
And this one too   

## Section Two

Content here.
EOF

# Verify violations exist before auto-fix
lint_before_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_before_exit=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $lint_before_exit -ne 0 ]]; then
    echo "  ✓ pre-auto-fix: violations detected"
    PASS=$((PASS + 1))
else
    echo "  ✗ pre-auto-fix: expected violations but got clean lint"
    FAIL=$((FAIL + 1))
fi

# Run auto-fix
npx markdownlint-cli2 --no-globs --fix "$TMPDIR_TEST/test.md" 2>/dev/null || true

# Verify violations resolved
lint_after_exit=0
npx markdownlint-cli2 --no-globs "$TMPDIR_TEST/test.md" 2>/dev/null || lint_after_exit=$?
assert_eq "post-auto-fix: no violations" "0" "$lint_after_exit"

# ---------------------------------------------------------------------------
# Test: Empty spec directory (EC9)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Empty spec directory ==="

TMPDIR_EMPTY=$(mktemp -d /tmp/mdlint-test-empty.XXXXXX)

# Stub call_llm so it's never called
call_llm() { echo "ERROR: call_llm should not be called" >&2; return 1; }

MARKDOWNLINT_MAX_ITERATIONS=5
exit_code=0
run_markdownlint_validation "$TMPDIR_EMPTY" 2>/dev/null || exit_code=$?
assert_eq "empty dir returns success" "0" "$exit_code"

rm -rf "$TMPDIR_EMPTY"

# ---------------------------------------------------------------------------
# Test: run_markdownlint_validation with auto-fixable violations
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Full validation loop (auto-fix only) ==="

TMPDIR_FULL=$(mktemp -d /tmp/mdlint-test-full.XXXXXX)

# Create a file with auto-fixable violations only
cat > "$TMPDIR_FULL/spec.md" << 'EOF'
# Test Spec

Content with trailing whitespace   

## Details

More content here.   
EOF

exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_FULL" 2>&1) || exit_code=$?
assert_eq "auto-fix validation succeeds" "0" "$exit_code"
assert_contains "reports success" "SUCCESS" "$output"

rm -rf "$TMPDIR_FULL"

# ---------------------------------------------------------------------------
# Test: Max iteration exhaustion (T018)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Max iteration exhaustion ==="

TMPDIR_EXHAUST=$(mktemp -d /tmp/mdlint-test-exhaust.XXXXXX)

# Create a file with a violation that auto-fix can't resolve and LLM can't fix
# (since call_llm is stubbed to fail)
# MD013 (line-length > 200) is NOT auto-fixable — requires intelligent line breaking
python3 -c "
print('# Heading')
print()
words = 'the quick brown fox jumps over the lazy dog and keeps running through the vast open fields '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
" > "$TMPDIR_EXHAUST/spec.md"

# Override call_llm to always fail (simulates LLM unavailability)
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_EXHAUST" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ exhaustion returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ exhaustion returns non-zero (got exit 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports failure" "FAILED" "$output"

rm -rf "$TMPDIR_EXHAUST"

# ---------------------------------------------------------------------------
# Test: Lint fails but violations unparseable (Comment 2 regression test)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Lint exit non-zero with unparseable output ==="

TMPDIR_UNPARSE=$(mktemp -d /tmp/mdlint-test-unparse.XXXXXX)

# Create a valid file so the function proceeds past the empty-dir guard
cat > "$TMPDIR_UNPARSE/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Override parse_markdownlint_output to always return empty (simulates
# an unexpected output format that the parser can't handle)
_orig_parse=$(declare -f parse_markdownlint_output)
parse_markdownlint_output() { echo ""; }

# Override npx to simulate lint failure with unparseable output:
# first call (--fix) succeeds, second call (check-only) fails
_npx_call_count=0
npx() {
    _npx_call_count=$((_npx_call_count + 1))
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    echo "some unexpected markdownlint output format"
    return 1
}

call_llm() { return 1; }
MARKDOWNLINT_MAX_ITERATIONS=2
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_UNPARSE" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ unparseable lint failure returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ unparseable lint failure should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports unparseable failure" "FAILED" "$output"

# Restore originals
eval "$_orig_parse"
unset -f npx
unset _npx_call_count

rm -rf "$TMPDIR_UNPARSE"

# ---------------------------------------------------------------------------
# Test: $SPEC_DIR scoping (T025 — files outside spec dir are not modified)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: SPEC_DIR scoping ==="

TMPDIR_SCOPE=$(mktemp -d /tmp/mdlint-test-scope.XXXXXX)
mkdir -p "$TMPDIR_SCOPE/specdir"

# Put a valid file in the spec dir
cat > "$TMPDIR_SCOPE/specdir/spec.md" << 'EOF'
# Valid Spec

Content here.
EOF

# Put a file with violations OUTSIDE spec dir
cat > "$TMPDIR_SCOPE/outside.md" << 'EOF'
no heading at start which is a violation   
EOF

OUTSIDE_BEFORE=$(cat "$TMPDIR_SCOPE/outside.md")

# Override call_llm to avoid actual LLM calls
call_llm() { return 1; }

MARKDOWNLINT_MAX_ITERATIONS=1
run_markdownlint_validation "$TMPDIR_SCOPE/specdir" 2>/dev/null || true

OUTSIDE_AFTER=$(cat "$TMPDIR_SCOPE/outside.md")

assert_eq "outside file unchanged" "$OUTSIDE_BEFORE" "$OUTSIDE_AFTER"

rm -rf "$TMPDIR_SCOPE"

# ---------------------------------------------------------------------------
# Test: MARKDOWNLINT_MAX_ITERATIONS validation (T026)
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: MARKDOWNLINT_MAX_ITERATIONS validation ==="

# Self-contained helper that mirrors the validation block in generate-spec-from-issue.sh
_test_validate_iterations() {
    local MARKDOWNLINT_MAX_ITERATIONS="$1"
    if ! [[ "$MARKDOWNLINT_MAX_ITERATIONS" =~ ^[0-9]+$ ]] || (( 10#$MARKDOWNLINT_MAX_ITERATIONS <= 0 )); then
        echo "WARNING"
        MARKDOWNLINT_MAX_ITERATIONS=5
    fi
    echo "$MARKDOWNLINT_MAX_ITERATIONS"
}

# Non-numeric value should fall back to default 5
result=$(_test_validate_iterations "abc")
TESTS_RUN=$((TESTS_RUN + 1))
if echo "$result" | grep -q "WARNING" && echo "$result" | grep -q "^5$"; then
    echo "  ✓ non-numeric value falls back to 5"
    PASS=$((PASS + 1))
else
    echo "  ✗ non-numeric value falls back to 5 (got: $result)"
    FAIL=$((FAIL + 1))
fi

# Zero should fall back to default
result=$(_test_validate_iterations "0")
TESTS_RUN=$((TESTS_RUN + 1))
if echo "$result" | grep -q "WARNING" && echo "$result" | grep -q "^5$"; then
    echo "  ✓ zero falls back to 5"
    PASS=$((PASS + 1))
else
    echo "  ✗ zero falls back to 5 (got: $result)"
    FAIL=$((FAIL + 1))
fi

# Valid positive integer should pass through unchanged
result=$(_test_validate_iterations "3")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$result" == "3" ]]; then
    echo "  ✓ valid value passes through"
    PASS=$((PASS + 1))
else
    echo "  ✗ valid value passes through (got: $result)"
    FAIL=$((FAIL + 1))
fi

# ---------------------------------------------------------------------------
# Test: strip_llm_preamble
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: strip_llm_preamble ==="

# T-preamble-1: No preamble (heading first line) — no-op
input_clean="# My Heading

Some content here."
result=$(strip_llm_preamble "$input_clean" "# My Heading" 2>/dev/null)
assert_eq "no preamble returns as-is" "$input_clean" "$result"

# T-preamble-2: Conversational preamble before heading
input_preamble="All 13 MD013 violations fixed — here is the corrected file:

# My Heading

Some content here."
expected_stripped="# My Heading

Some content here."
result=$(strip_llm_preamble "$input_preamble" "# My Heading" 2>/dev/null)
assert_eq "strips preamble before heading" "$expected_stripped" "$result"

# T-preamble-3: Preamble with original file starting with heading (strategy 1)
input_preamble3="Sure, here is the fixed file:
# Requirements Checklist

- Item 1
- Item 2"
expected3="# Requirements Checklist

- Item 1
- Item 2"
result=$(strip_llm_preamble "$input_preamble3" "# Requirements Checklist" 2>/dev/null)
assert_eq "strips conversational prefix" "$expected3" "$result"

# T-preamble-4: Preamble with list-start (strategy 2, no heading in original)
input_list="Good, I have fixed the violations:
- Item 1
- Item 2"
expected_list="- Item 1
- Item 2"
result=$(strip_llm_preamble "$input_list" "- Item 1" 2>/dev/null)
assert_eq "strips preamble before list" "$expected_list" "$result"

# T-preamble-5: Empty input returns empty
result=$(strip_llm_preamble "" "" 2>/dev/null)
assert_eq "empty input returns empty" "" "$result"

# T-preamble-6: Blockquote start is valid markdown
input_bq="> This is a quote"
result=$(strip_llm_preamble "$input_bq" "> Original" 2>/dev/null)
assert_eq "blockquote is valid md start" "$input_bq" "$result"

# T-preamble-7: Code fence start is valid markdown
input_fence="\`\`\`python
print('hello')
\`\`\`"
result=$(strip_llm_preamble "$input_fence" "\`\`\`python" 2>/dev/null)
assert_eq "code fence is valid md start" "$input_fence" "$result"

# T-preamble-8: Multi-line preamble stripped
input_multi="I have reviewed the file.
All violations have been resolved.
Here is the corrected version:

# Document Title

Content."
expected_multi="# Document Title

Content."
result=$(strip_llm_preamble "$input_multi" "# Document Title" 2>/dev/null)
assert_eq "multi-line preamble stripped" "$expected_multi" "$result"

# T-preamble-9: Warns about preamble on stderr
warn_output=$(strip_llm_preamble "Certainly! Here is the fix:
# Heading" "# Heading" 2>&1 >/dev/null)
assert_contains "logs preamble warning" "preamble detected" "$warn_output"

# T-preamble-10: Leading blank line should not bypass preamble stripping
input_blank_lead="
All violations fixed!
# My Heading

Content."
expected_blank_lead="# My Heading

Content."
result=$(strip_llm_preamble "$input_blank_lead" "# My Heading" 2>/dev/null)
assert_eq "blank first line does not bypass stripping" "$expected_blank_lead" "$result"

# T-preamble-10b: Leading blank lines alone should be trimmed before valid markdown
input_blank_only="
# Heading

Content."
expected_blank_only="# Heading

Content."
result=$(strip_llm_preamble "$input_blank_only" "# Heading" 2>/dev/null)
assert_eq "blank lines before valid markdown are trimmed" "$expected_blank_only" "$result"

# T-preamble-11: h3+ headings are recognised as valid markdown start
input_h3="### Sub Heading

Content."
result=$(strip_llm_preamble "$input_h3" "### Sub Heading" 2>/dev/null)
assert_eq "h3 heading is valid md start" "$input_h3" "$result"

# T-preamble-12: HTML comment start is valid markdown (no preamble — no-op)
input_comment="<!-- markdownlint-disable MD013 -->
# My Heading

Content."
result=$(strip_llm_preamble "$input_comment" "<!-- markdownlint-disable MD013 -->" 2>/dev/null)
assert_eq "HTML comment is valid md start" "$input_comment" "$result"

# T-preamble-13: Preamble before HTML comment is stripped
input_comment_preamble="Sure, here is the corrected file:
<!-- markdownlint-disable MD013 -->
# My Heading

Content."
expected_comment_preamble="<!-- markdownlint-disable MD013 -->
# My Heading

Content."
result=$(strip_llm_preamble "$input_comment_preamble" "<!-- markdownlint-disable MD013 -->" 2>/dev/null)
assert_eq "strips preamble before HTML comment" "$expected_comment_preamble" "$result"

# T-preamble-14: + list marker is valid markdown start (no-op)
input_plus_list="+ Item one
+ Item two"
result=$(strip_llm_preamble "$input_plus_list" "+ Item one" 2>/dev/null)
assert_eq "plus list marker is valid md start" "$input_plus_list" "$result"

# T-preamble-15: Ordered list with space is valid markdown start (no-op)
input_ordered="1. First item
2. Second item"
result=$(strip_llm_preamble "$input_ordered" "1. First item" 2>/dev/null)
assert_eq "ordered list is valid md start" "$input_ordered" "$result"

# T-preamble-16: Dot without trailing space is NOT valid markdown (e.g. version strings)
input_version="2024.04 release notes
# Heading

Content."
expected_version="# Heading

Content."
result=$(strip_llm_preamble "$input_version" "# Heading" 2>/dev/null)
assert_eq "version-like line is not valid md start" "$expected_version" "$result"

# ---------------------------------------------------------------------------
# Test: Violation-count stall detection
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Violation-count stall detection ==="

TMPDIR_COUNTSTALL=$(mktemp -d /tmp/mdlint-test-countstall.XXXXXX)

# Create a file with a violation that auto-fix can't resolve
python3 -c "
print('# Heading')
print()
words = 'the quick brown fox jumps over the lazy dog and keeps running through the vast open fields '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
" > "$TMPDIR_COUNTSTALL/spec.md"

# Stub npx/markdownlint so this test doesn't depend on the real linter.
# First call per iteration is --fix (no-op); second is check-only which
# returns a synthetic violation whose line number shifts each call (so
# fingerprints change) but the violation count stays at 1.
_countstall_npx_file=$(mktemp /tmp/mdlint-countstall-npx.XXXXXX)
echo "0" > "$_countstall_npx_file"
npx() {
    local n
    n=$(cat "$_countstall_npx_file")
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    n=$((n + 1))
    echo "$n" > "$_countstall_npx_file"
    # Emit a synthetic violation at a shifting line number
    local vline=$((10 + n))
    echo "$TMPDIR_COUNTSTALL/spec.md:${vline}:1 MD013/line-length Line length [Expected: 200; Actual: 250]"
    return 1
}

# Override call_llm to return content with violations at *different* line
# numbers each time (so fingerprints change) but the same violation count.
# This simulates the LLM introducing new violations while fixing others.
# We use a file-based counter since call_llm runs in a subshell.
_countstall_file=$(mktemp /tmp/mdlint-countstall-counter.XXXXXX)
echo "0" > "$_countstall_file"
call_llm() {
    local n
    n=$(cat "$_countstall_file")
    n=$((n + 1))
    echo "$n" > "$_countstall_file"
    python3 -c "
print('# Heading')
print()
# Add varying short paragraphs so the long line ends up on different lines
for i in range($n + 1):
    print('Short paragraph ' + str(i) + '.')
    print()
words = 'different long text that exceeds the line length limit by a lot because we keep adding more words '
line = ''
while len(line) < 220:
    line += words
print(line.strip())
"
}

MARKDOWNLINT_MAX_ITERATIONS=5
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_COUNTSTALL" 2>&1) || exit_code=$?

TESTS_RUN=$((TESTS_RUN + 1))
if [[ $exit_code -ne 0 ]]; then
    echo "  ✓ count-stall returns non-zero"
    PASS=$((PASS + 1))
else
    echo "  ✗ count-stall should return non-zero (got 0)"
    FAIL=$((FAIL + 1))
fi

assert_contains "reports stall in output" "Stall detected" "$output"

# Should not exhaust all 5 iterations — stall should trigger earlier
assert_contains "exits before max iterations" "violation count has not decreased" "$output"

unset -f npx
rm -rf "$TMPDIR_COUNTSTALL"
rm -f "$_countstall_file"
rm -f "$_countstall_npx_file"

# ---------------------------------------------------------------------------
# Test: Whitespace-only LLM output should not overwrite file
# ---------------------------------------------------------------------------
echo ""
echo "=== Test: Whitespace-only LLM output guard ==="

TMPDIR_WSGUARD=$(mktemp -d /tmp/mdlint-test-wsguard.XXXXXX)

# Create a markdown file with a violation
printf '# Heading\n\n%s\n' "$(printf '%0.sX' {1..250})" > "$TMPDIR_WSGUARD/spec.md"
original_content=$(cat "$TMPDIR_WSGUARD/spec.md")

# Stub npx: first call (--fix) is no-op, second (check-only) reports a violation,
# subsequent calls report clean so the loop terminates.
_wsguard_npx_file=$(mktemp /tmp/mdlint-wsguard-npx.XXXXXX)
echo "0" > "$_wsguard_npx_file"
npx() {
    local n
    n=$(cat "$_wsguard_npx_file")
    n=$((n + 1))
    echo "$n" > "$_wsguard_npx_file"
    if [[ "$*" == *"--fix"* ]]; then
        return 0
    fi
    if [[ $n -le 2 ]]; then
        echo "$TMPDIR_WSGUARD/spec.md:3:1 MD013/line-length Line length [Expected: 200; Actual: 250]"
        return 1
    fi
    return 0
}

# Override call_llm to return whitespace-only content
call_llm() {
    printf '\n   \n\n'
}

MARKDOWNLINT_MAX_ITERATIONS=3
exit_code=0
output=$(run_markdownlint_validation "$TMPDIR_WSGUARD" 2>&1) || exit_code=$?

assert_contains "logs whitespace-only warning" "blank or whitespace-only" "$output"

# Verify original file content was preserved (not overwritten with whitespace)
current_content=$(cat "$TMPDIR_WSGUARD/spec.md")
TESTS_RUN=$((TESTS_RUN + 1))
if [[ "$current_content" == "$original_content" ]]; then
    echo "  ✓ file not overwritten with whitespace-only content"
    PASS=$((PASS + 1))
else
    echo "  ✗ file was overwritten despite whitespace-only LLM output"
    FAIL=$((FAIL + 1))
fi

unset -f npx
rm -rf "$TMPDIR_WSGUARD"
rm -f "$_wsguard_npx_file"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "======================================="
echo "Tests: $TESTS_RUN  Passed: $PASS  Failed: $FAIL"
echo "======================================="

if [[ $FAIL -gt 0 ]]; then
    exit 1
fi
exit 0
