"""Generator for ``agentic-devtools-configured-setup.py``.

The generated script installs only the tools the user selected during
``agdt-setup``.  Output is stdlib-only and idempotent.
"""

from __future__ import annotations

from .constants import TOOL_REGISTRY


def render_tool_installs(selected_tools: list[str]) -> str:
    """Return a snippet of Python source that installs the *selected_tools*.

    Each tool is installed via ``subprocess.run`` with a human-readable
    header.  Unknown tool names are silently skipped.

    For pip-based installs the generated code uses
    ``[sys.executable, "-m", "pip", ...]`` so that packages are installed
    into the same environment as the running interpreter.
    """
    lines: list[str] = []
    for tool_name in selected_tools:
        entry = TOOL_REGISTRY.get(tool_name)
        if entry is None:
            continue
        argv: list[str] = list(entry["install_argv"])  # type: ignore[arg-type]
        # For pip installs, prefix with sys.executable so the correct
        # interpreter is always used regardless of PATH.
        if argv and argv[0] == "pip":
            argv_expr = f"[sys.executable, \"-m\", {', '.join(repr(a) for a in argv)}]"
            shell_expr = ""
        else:
            # Non-pip tools (e.g. npm) are batch scripts on Windows and
            # require shell=True to locate the .cmd wrapper.
            argv_expr = repr(argv)
            shell_expr = ", shell=(sys.platform == \"win32\")"
        lines.append(f"    # {entry['description']}")
        lines.append(f'    print("Installing {tool_name}...")')
        lines.append(f"    result = subprocess.run({argv_expr}{shell_expr})")
        lines.append("    if result.returncode != 0:")
        lines.append(f'        print("  \u2717 Failed to install {tool_name}", file=sys.stderr)')
        lines.append("        sys.exit(1)")
        lines.append("")
    return "\n".join(lines)


def generate_configured_setup_script(selected_tools: list[str] | None = None) -> str:
    """Return the full content of ``agentic-devtools-configured-setup.py``.

    Args:
        selected_tools: List of tool names from the tool registry.
            If ``None`` or empty, the script body is a no-op with an
            informational message.
    """
    if not selected_tools:
        tool_body = '    print("  ℹ No optional tools configured. Re-run agdt-setup to select tools.")'
    else:
        tool_body = render_tool_installs(selected_tools)
        if not tool_body.strip():
            tool_body = '    print("  ℹ No optional tools configured. Re-run agdt-setup to select tools.")'
    return _CONFIGURED_TEMPLATE.format(tool_body=tool_body)


_CONFIGURED_TEMPLATE = '''\
#!/usr/bin/env python3
"""agentic-devtools configured setup — optional tool installation.

This script is generated by ``agdt-setup`` based on your tool
selections.  It is regenerated on every ``agdt-setup`` run.
DO NOT EDIT — your changes will be overwritten.

Supports: ``--foreground`` (default, forward-compatible no-op).
"""

import argparse
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser(
        description="agentic-devtools configured setup — optional tool installation.",
    )
    parser.add_argument(
        "--foreground", action="store_true", default=True,
        help="Run in foreground (default, forward-compatible).",
    )
    parser.parse_args()

    print("─── agentic-devtools Configured Setup ───────────────────────")
    print()

{tool_body}

    print()
    print("─── Configured Setup Complete ───────────────────────────────")


if __name__ == "__main__":
    main()
'''
